version: "3.9"

services:
  goapp:
    image: andregri/goapp:1.0
    build:
      context: .
    
    ports:
      - 9000:9000

    environment:
      POSTGRES_USER: andrea
      POSTGRES_PASSWORD: very_strong_password
      POSTGRES_DB: app_database
      POSTGRES_HOST: db # Name of the db service

    depends_on:
      - db

  db:
    image: 'postgres:latest'

    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: andrea
      POSTGRES_PASSWORD: very_strong_password
      POSTGRES_DB: app_database

    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}